name: Sort JSON Files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sort-json:
    runs-on: self-hosted
    container:
      image: alpine:latest
    env:
      CHANGES: 1

    steps:
    - name: Test Changes
      run: |
        if ${{ env.CHANGES }} ; then
          echo "Currently ${{ env.CHANGES }} Change to empty"
          echo "CHANGES=" >> "$GITHUB_ENV"
        else
          echo "Currently ${{ env.CHANGES }} Change to 1"
          echo "CHANGES=1" >> "$GITHUB_ENV"
        fi

    - name: Run if Changes
      if: env.CHANGES
      run: |
        echo "$CHANGES vs ${{ env.CHANGES }} Running!"
