name: Sort JSON Files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sort-json:
    runs-on: self-hosted
    container:
      image: alpine:latest
    env:
      CHANGES: 1

    steps:
    - name: Test Changes
      run: |
        if CHANGES ; then
          echo "Currently ${{ env.CHANGES }} Change to empty"
          env.CHANGES=""
        else
          echo "Currently ${{ env.CHANGES }} Change to 1"
          env.CHANGES=1
        fi

    - name: Run if Changes
      if: env.CHANGES
      run: |
        echo "$CHANGES vs ${{ env.CHANGES }} Running!"
