name: Sort JSON Files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sort-json:
    runs-on: self-hosted
    container:
      image: alpine:latest
    env:
      CHANGES: ""        
    permissions:
        contents: write
    steps:
    - name: Install jq and git
      run: apk add --no-cache jq git
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Sort JSON files
      run: |
        for file in $(find . -name "*.json"); do
          jq -S . "$file" > "$file.dftmp"
          if ! diff "$file" "$file.dftmp"; then
            mv "$file.dftmp" "$file"
            echo "CHANGES to $file"
            echo "CHANGES=true" >> "$GITHUB_ENV"
          else
            echo "no changes $file"
            rm "$file.dftmp"
          fi
        done

    - name: Commit Sorted JSON file changes
      if: env.CHANGES
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sort JSON files $(date +%F)"
          git push origin HEAD
        else
          echo "ERROR: Unable to find changes to commit."
          exit 1
        fi
